# Generated by Django 6.0.6 on 2026-06-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_intent_id',
            new_name='cinetpay_transaction_id',
        ),
    ]
