# Generated by Django 6.0.6 on 2026-06-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='certification_label',
        ),
    ]
